server:
  port: 8082
spring:
  application:
    name: food
  datasource:
    # Username and secret
    username: postgres
    password: 1234
    # Connection url
    url: jdbc:postgresql://localhost:5432/app_user

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "update" the database
      # schema will be automatically updated accordingly to java entities found in
      # the project
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    # Show or not log for each sql query
    show-sql: true